name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore .NET dependencies
      run: dotnet restore TaskManagement.Api/TaskManagement.Api.csproj

    - name: Build the backend
      run: dotnet build TaskManagement.Api/TaskManagement.Api.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test TaskManagement.Tests/TaskManagement.Tests.csproj --configuration Release --no-build --verbosity normal

    - name: Build Docker images
      run: |
        docker-compose build

    - name: Push Docker images
      run: |
        docker-compose push
